version: '3.3'

services:
   mysql-container:
     image: mysql:5.7
     volumes:
       - /home/database/mysql:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: 123
       MYSQL_DATABASE: little_pigs
       MYSQL_USER: root
       MYSQL_PASSWORD: 123